#!/usr/bin/env python3
"""Regenerate queries/*.md cross-reference indices from page frontmatter.

Produces:
  queries/by-problem.md          symptom -> pattern page -> candidate techniques
  queries/by-technique.md        technique -> pages using it
  queries/by-hardware-feature.md hardware feature -> pages
  queries/by-kernel-type.md      kernel type -> pages
  queries/by-language.md         language/DSL -> pages
  queries/by-repo.md             repo -> all PR pages

Do not edit queries/*.md by hand; rerun this script.
"""

import re
import sys
import yaml
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _wiki_root import WIKI_ROOT  # noqa: E402
from _scope import is_active  # noqa: E402

GEN_NOTE = "<!-- AUTO-GENERATED by scripts/generate-indices.py. Do not edit by hand. -->\n"


def load_pages():
    pages = []
    for subdir in ("sources", "wiki"):
        base = WIKI_ROOT / subdir
        if not base.exists():
            continue
        for md in sorted(base.rglob("*.md")):
            content = md.read_text(encoding="utf-8")
            m = re.match(r'^---\s*\r?\n(.*?)\r?\n---\s*\r?\n', content, re.DOTALL)
            if not m:
                continue
            try:
                fm = yaml.safe_load(m.group(1))
            except yaml.YAMLError:
                continue
            if not isinstance(fm, dict):
                continue
            if not is_active(fm):
                continue
            # Query pages are Markdown and their links must use URL-style paths
            # regardless of the host OS used to regenerate them.
            pages.append({"path": md.relative_to(WIKI_ROOT).as_posix(), "fm": fm})
    return pages


def ptype(p):
    fm = p["fm"]
    if "type" in fm:
        return f"wiki-{fm['type']}"
    parts = p["path"].split("/")
    if parts[0] == "sources":
        return f"source-{parts[1].rstrip('s')}"
    return "unknown"


def link(p):
    fm = p["fm"]
    return f"[{fm.get('id','?')}]({p['path']}) — {fm.get('title','')}"


def write(path, lines):
    (WIKI_ROOT / path).write_text(GEN_NOTE + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path}")


def main():
    pages = load_pages()
    wiki_pages = [p for p in pages if ptype(p).startswith("wiki-")]

    # by-technique
    tech = defaultdict(list)
    for p in pages:
        for t in (p["fm"].get("techniques") or []):
            tech[t].append(p)
    lines = ["# Index: By Technique", "",
             "Every page (wiki + PR sources) that uses each optimization technique.", ""]
    for t in sorted(tech):
        lines.append(f"## {t}")
        lines.append("")
        for p in sorted(tech[t], key=lambda x: x["path"]):
            lines.append(f"- {link(p)}  `[{ptype(p)}]`")
        lines.append("")
    write("queries/by-technique.md", lines)

    # by-hardware-feature
    hw = defaultdict(list)
    for p in pages:
        for f in (p["fm"].get("hardware_features") or []):
            hw[f].append(p)
    lines = ["# Index: By Hardware Feature", "",
             "Pages grouped by AMD GPU hardware feature.", ""]
    for f in sorted(hw):
        lines.append(f"## {f}")
        lines.append("")
        for p in sorted(hw[f], key=lambda x: x["path"]):
            lines.append(f"- {link(p)}  `[{ptype(p)}]`")
        lines.append("")
    write("queries/by-hardware-feature.md", lines)

    # by-kernel-type
    kt = defaultdict(list)
    for p in pages:
        for k in (p["fm"].get("kernel_types") or []):
            kt[k].append(p)
    lines = ["# Index: By Kernel Type", ""]
    for k in sorted(kt):
        lines.append(f"## {k}")
        lines.append("")
        for p in sorted(kt[k], key=lambda x: x["path"]):
            lines.append(f"- {link(p)}  `[{ptype(p)}]`")
        lines.append("")
    write("queries/by-kernel-type.md", lines)

    # by-language
    lang = defaultdict(list)
    for p in pages:
        for l in (p["fm"].get("languages") or []):
            lang[l].append(p)
    lines = ["# Index: By Language / DSL", ""]
    for l in sorted(lang):
        lines.append(f"## {l}")
        lines.append("")
        for p in sorted(lang[l], key=lambda x: x["path"]):
            lines.append(f"- {link(p)}  `[{ptype(p)}]`")
        lines.append("")
    write("queries/by-language.md", lines)

    # by-problem (patterns)
    lines = ["# Index: By Problem (Symptom → Pattern → Techniques)", ""]
    pats = [p for p in wiki_pages if ptype(p) == "wiki-pattern"]
    sym = defaultdict(list)
    for p in pats:
        for s in (p["fm"].get("symptoms") or []):
            sym[s].append(p)
    for s in sorted(sym):
        lines.append(f"## symptom: {s}")
        lines.append("")
        for p in sym[s]:
            fm = p["fm"]
            lines.append(f"- {link(p)}")
            cts = fm.get("candidate_techniques") or []
            if cts:
                lines.append(f"  - candidate techniques: {', '.join(cts)}")
        lines.append("")
    write("queries/by-problem.md", lines)

    # by-repo (PR sources)
    repo = defaultdict(list)
    for p in pages:
        if ptype(p) == "source-pr":
            repo[p["fm"].get("repo", "?")].append(p)
    lines = ["# Index: By Repository (PR sources)", "",
             f"{sum(len(v) for v in repo.values())} PR pages across {len(repo)} repositories.", ""]
    for r in sorted(repo):
        anchor = r.lower().replace("/", "").replace("-", "").replace("_", "")
        lines.append(f"## {r}")
        lines.append("")
        lines.append(f"{len(repo[r])} PR page(s).")
        lines.append("")
        for p in sorted(repo[r], key=lambda x: int(x["fm"].get("pr", 0))):
            fm = p["fm"]
            lines.append(f"- [PR #{fm.get('pr')}]({p['path']}) — {fm.get('title','')}")
        lines.append("")
    write("queries/by-repo.md", lines)


if __name__ == "__main__":
    main()
